backend:
  name: git-gateway
  branch: main  
# when using the default proxy server port
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "home"
    label: "Home Page"
    folder: "content"
    path: "_index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime"}
  - name: "product"
    label: "Product Page"
    folder: "content/products"
    media_folder: "static/images/products" # Folder where user uploaded files should go
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "string" }      
      - { label: "Product Price", name: "price", widget: "string" }      
      - { label: "Price Before", name: "priceBefore", widget: "string" }
      - { label: "Product Short Description", name: "productShortDescription", widget: "string" }
      - { label: "Product ID", name: "productId", widget: "uuid"}
      - { label: "Type", name: "type", widget: "hidden", default: "Products"}
      - { label: "Product Images", name: "productImages", widget: "image"}
      