backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "new_arrivals" # Used in routes, e.g., /admin/collections/post
    label: "New Arrivals" # Used in the UI
    folder: "content/new_arrivals" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter    
      - {
          label: "Product 1",
          name: "product_1",
          widget: "object",
          fields:
            [
              { label: "Product Name", name: "product_name1", widget: "string" },
              { label: "Price", name: "price1", widget: "string" },
              { label: "Discount Price", name: "discount_price1", widget: "string" },
              { label: "Image", name: "image1", widget: "image" },
            ],
        }
      - {
          label: "Product 2",
          name: "product_2",
          widget: "object",
          fields:
            [
              { label: "Product Name", name: "product_name2", widget: "string" },
              { label: "Price", name: "price2", widget: "string" },
              { label: "Discount Price", name: "discount_price2", widget: "string" },
              { label: "Image", name: "image2", widget: "image" },
            ],
        }
      - {
          label: "Product 3",
          name: "product_3",
          widget: "object",
          fields:
            [
              { label: "Product Name", name: "product_name3", widget: "string" },
              { label: "Price", name: "price3", widget: "string" },
              { label: "Discount Price", name: "discount_price3", widget: "string" },
              { label: "Image", name: "image3", widget: "image" },
            ],
        }
      - {
          label: "Product 4",
          name: "product_4",
          widget: "object",
          fields:
            [
              { label: "Product Name", name: "product_name4", widget: "string" },
              { label: "Price", name: "price4", widget: "string" },
              { label: "Discount Price", name: "discount_price4", widget: "string" },
              { label: "Image", name: "image4", widget: "image" },
            ],
        }
      - {
          label: "Product 5",
          name: "product_5",
          widget: "object",
          fields:
            [
              { label: "Product Name", name: "product_name5", widget: "string" },
              { label: "Price", name: "price5", widget: "string" },
              { label: "Discount Price", name: "discount_price5", widget: "string" },
              { label: "Image", name: "image5", widget: "image" },
            ],
        }
      - {
          label: "Product 6",
          name: "product_6",
          widget: "object",
          fields:
            [
              { label: "Product Name", name: "product_name6", widget: "string" },
              { label: "Price", name: "price6", widget: "string" },
              { label: "Discount Price", name: "discount_price6", widget: "string" },
              { label: "Image", name: "image6", widget: "image" },
            ],
        }
      - {
          label: "Product 7",
          name: "product_7",
          widget: "object",
          fields:
            [
              { label: "Product Name", name: "product_name7", widget: "string" },
              { label: "Price", name: "price7", widget: "string" },
              { label: "Discount Price", name: "discount_price7", widget: "string" },
              { label: "Image", name: "image7", widget: "image" },
            ],
        }
      - {
          label: "Product 8",
          name: "product_8",
          widget: "object",
          fields:
            [
              { label: "Product Name", name: "product_name8", widget: "string" },
              { label: "Price", name: "price8", widget: "string" },
              { label: "Discount Price", name: "discount_price8", widget: "string" },
              { label: "Image", name: "image8", widget: "image" },
            ],
        }        
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
